### ISSUE TITLE
Implementing DiffuseKronA paper

### ISSUE THREAD

**Issue by omer-polar** [KohakuBlueleaf/LyCORIS#164]
Have you seen this paper? Is there a way to implement the method described here (https://arxiv.org/pdf/2402.17412.pdf - Page 29 Appendix F) into the LoKr script without much changes to the codebase? They are not suggesting anything new, just an observation that a non-square A matrix (4,64) or (8, 64) performs better than the factorization method implemented in LyCORIS. Kinda like the best of both LoKr with a low factor and a high factor. I guess one could directly change factorization method and it would work, but I'm more worried about the compatibility of the resulting LoKr with inference libraries (comfy etc.).

**Comment by KohakuBlueleaf** [comment]
1. no, for almost same param count it will be almost same as lokr. non-square C matrix (noted: in our paper the smaller matrix is C) will not make it significantly better. We already try that almost 10month ago. Maybe it will be more flexible/stable on different hyperparameters. But the "observation" of performs better doesn't mean anything. If you want to deny me, use same evaluation framework we introduce in LyCORIS' paper to test it.
2. You don't need to worry about comfy since more than 50% algo implemented in LyCORIS are not supported in comfy (train_norm, OFT/BOFT/IA3, DoRA/DoHa/DoKr, etc...). And sd-webui's built-in lora system is fully maintained by me, so all the new algorithm will definitely implemented into that.
  * And actually this unbalanced factorization don't need any modification for inference.
3. I can implement unbalanced factorization, which is very easy.

And some clarification here:
I will implement it but I will never call it as "DiffuseKronA". Also it has very low priority. Any further issue and Pull Request mentioned DiffuseKronA will be closed directly.

Unless the authors admit LyCORIS is not "simultaneous work" but "Previous work". 
The authors claim that LyCORIS' lokr is "simultaneous work" and claim their works started at "2023/05".
BUT, LyCORIS lokr is "implemented and open sourced" at "early 2023/04"

Also our paper is published at least 2 month earlier than DiffuseKronA.

I will close this issue immediately. If you want to track the progress of unbalanced factorization, just open a new issue.

**Comment by KohakuBlueleaf** [comment]
unbalanced_factorization implemented in `2.3.0.dev1`

**Comment by omer-polar** [comment]
Thanks a lot for the clarification and this amazing library! I didn't mean no disrespect. I also found it weird that they chose to rename the method when in fact it's more of a follow-up work to LoKr.
