### ISSUE TITLE
BOFT training

### ISSUE THREAD

**Issue by iqddd** [KohakuBlueleaf/LyCORIS#178]
Based on the training speed, sample generation speed, and final file size compared to Diag-OFT, it appears that BOFT-training has switched to float32. Is there a possibility to implement mixed precision?

upd: It doesn't seem that the issue is related to switching to float32 or disabling mixed precision. The problem is likely due to the algorithm itself or its unoptimized implementation. BOFT training is approximately 1.8 times slower than Diag-OFT and more than twice as slow as regular LoRa.
Can we expect any improvements on this?

**Comment by KohakuBlueleaf** [comment]
BOFT itself is very large. few times larger than OFT if you use same block size.
Plz check their paper and you know what I'm talking about

I will add some more option for detailed control on how many layer you want instead of always give out dense mat.

But I need to say, if you are asking "improvements on speed" for same config. It is almost impossible.

If you are asking "improvements on more options so user can get smaller/faster BOFT" then it is possible.

But I need to say what you encountered is expected. BOFT can be seen as multi stage Diag-OFT. It should be way slower/larger than Diag-OFT.
