### ISSUE TITLE
Does LoKr support to wrap a LLM Model?

### ISSUE THREAD

**Issue by WhuanY** [KohakuBlueleaf/LyCORIS#220]
Thanks for your amazing work! As title mentioned, my task is to successfully fine-tune a large language model via diffrent lora-like adapters. Currently I am exploring Finetuning LoKr on [our customized model](https://github.com/RUC-GSAI/YuLan-Chat) via different framework(i.e.: torch, paddle). 

Is there any documentation reference that tells me how to apply LoKr adapter on such a LLM? I used the LoKr API from HuggingFace recently, but it seems that there are bugs, which I guess due to the Hf developers didn't test LoKr on any LLMs([See here for why I think so](https://github.com/huggingface/peft/issues/2147). Thanks.

**Comment by KohakuBlueleaf** [comment]
1. In HakuPhi I already show how to use lycoris on LLM.
2. LyCORIS is now designed to be a general PEFT library to wrap ALL the pytorch module. not matter what it is for. We just won't ensure the performance will surpass or on par with the algo that LyCORIS didn't implement.
3. Check the example, if your model is implemented in pytorch and you are using custom attention (instead of pytorch MHA). It will definitely work.

**Comment by WhuanY** [comment]
> 3. Check the example, if your model is implemented in pytorch and you are using custom attention (instead of pytorch MHA). It will definitely work.

Thanks. By saying "pytorch MHA", could I just make sure you are refering to [pytorch MHA](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention) ?

Knowing that would be of great help. Thanks!

**Comment by KohakuBlueleaf** [comment]
Yes, pytorch's MHA make q,k,v together (not always) which make things tricky.
